version: "3"

services:
  app:
    build: .
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - OTEL_SERVICE_NAME=otel-quickstart-spring-boot
      - OTEL_METRIC_EXPORT_INTERVAL=5000
      - OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION=BASE2_EXPONENTIAL_BUCKET_HISTOGRAM
    volumes:
      - logs:/var/log:rw
    ports:
      - 8080:8080

volumes:
  logs:
